const $=id=>document.getElementById(id);
const KEY='share-mind-small-pieces-v1';
let state={version:1,title:'',items:[]},selected=null,removed=null,saveTimer;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function status(text){$('status').textContent=text;}
try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.version===1&&Array.isArray(s.items)&&s.items.length<=12){state={version:1,title:String(s.title||'').slice(0,80),items:s.items.filter(i=>typeof i.id==='string'&&typeof i.src==='string'&&(/^(data:image\/(png|jpeg|webp);base64,)/.test(i.src)||/^assets\/[a-z-]+\.png$/.test(i.src))).map(i=>({...i,x:clamp(Number(i.x)||50,5,95),y:clamp(Number(i.y)||50,5,95),size:clamp(Number(i.size)||24,10,50),rotation:clamp(Number(i.rotation)||0,-180,180),float:!!i.float}))};}}catch{status('Could not restore this browser’s saved collage.');}
function persist(){clearTimeout(saveTimer);try{localStorage.setItem(KEY,JSON.stringify(state));status('Saved on this browser');}catch{status('Not saved: browser storage is full or unavailable. Export a JSON backup.');}}
function saveSoon(){clearTimeout(saveTimer);saveTimer=setTimeout(persist,200);}
function current(){return state.items.find(i=>i.id===selected);}
function position(el,item){el.style.left=item.x+'%';el.style.top=item.y+'%';el.style.width=item.size+'%';el.style.setProperty('--rotation',item.rotation+'deg');el.style.setProperty('--delay',-(state.items.indexOf(item)%4)+'s');el.classList.toggle('floating',item.float);}
function controls(){const i=current();$('controls').disabled=!i;$('selectHint').textContent=i?i.name:'Click a piece on the canvas to adjust it.';if(i){$('size').value=i.size;$('sizeValue').value=Math.round(i.size)+'%';$('rotation').value=i.rotation;$('rotationValue').value=Math.round(i.rotation)+'°';$('float').checked=i.float;}for(const el of $('board').querySelectorAll('.piece')){el.classList.toggle('selected',el.dataset.id===selected);el.setAttribute('aria-pressed',String(el.dataset.id===selected));}}
function select(id){selected=id;controls();}
function draw(){for(const el of $('board').querySelectorAll('.piece'))el.remove();for(const i of state.items){const el=document.createElement('button');el.className='piece';el.dataset.id=i.id;el.setAttribute('aria-label',i.name+'; use arrow keys to move');const img=document.createElement('img');img.src=i.src;img.alt='';img.draggable=false;el.append(img);position(el,i);el.addEventListener('click',()=>select(i.id));el.addEventListener('pointerdown',e=>{if(e.button!==0)return;select(i.id);const r=$('board').getBoundingClientRect(),start={x:e.clientX,y:e.clientY,ix:i.x,iy:i.y};el.setPointerCapture(e.pointerId);const move=ev=>{i.x=clamp(start.ix+(ev.clientX-start.x)/r.width*100,5,95);i.y=clamp(start.iy+(ev.clientY-start.y)/r.height*100,5,95);position(el,i);};const end=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',end);el.removeEventListener('pointercancel',end);persist();};el.addEventListener('pointermove',move);el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);});el.addEventListener('keydown',e=>{const v=e.shiftKey?5:1;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();select(i.id);i.x=clamp(i.x+(e.key==='ArrowLeft'?-v:e.key==='ArrowRight'?v:0),5,95);i.y=clamp(i.y+(e.key==='ArrowUp'?-v:e.key==='ArrowDown'?v:0),5,95);position(el,i);persist();}});$('board').append(el);}$('count').textContent=state.items.length+' / 12 pieces';$('empty').hidden=state.items.length>0;controls();}
function add(src,name){if(state.items.length>=12){status('The canvas holds 12 pieces. Remove one before adding another.');return false;}const i={id:crypto.randomUUID(),name:String(name).slice(0,80),src,x:35+(state.items.length*13)%35,y:35+(state.items.length*17)%35,size:26,rotation:0,float:false};state.items.push(i);selected=i.id;draw();persist();return true;}
$('board').addEventListener('click',e=>{if(e.target===$('board'))select(null);});
for(const [id,key] of [['size','size'],['rotation','rotation'],['float','float']])$(id).addEventListener('input',()=>{const i=current();if(!i)return;i[key]=id==='float'?$(id).checked:Number($(id).value);position($('board').querySelector(`[data-id="${i.id}"]`),i);controls();saveSoon();});
$('front').onclick=()=>{const i=current();if(!i)return;state.items=state.items.filter(x=>x.id!==i.id);state.items.push(i);draw();persist();};
$('remove').onclick=()=>{const i=current();if(!i)return;removed={item:i,index:state.items.indexOf(i)};state.items=state.items.filter(x=>x.id!==i.id);selected=null;$('undo').hidden=false;draw();persist();};
$('undo').onclick=()=>{if(!removed||state.items.length>=12)return;state.items.splice(removed.index,0,removed.item);selected=removed.item.id;removed=null;$('undo').hidden=true;draw();persist();};
$('title').value=state.title;$('title').addEventListener('input',()=>{state.title=$('title').value;saveSoon();});
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='small-pieces.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function imageData(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Please choose a PNG, JPG or WebP image.');if(file.size>15000000)throw Error('Please choose images smaller than 15 MB.');const bmp=await createImageBitmap(file);if(bmp.width*bmp.height>40000000){bmp.close();throw Error('That image is too large. Try a smaller copy.');}const canvas=document.createElement('canvas'),ratio=Math.min(1,420/Math.max(bmp.width,bmp.height));canvas.width=Math.max(1,Math.round(bmp.width*ratio));canvas.height=Math.max(1,Math.round(bmp.height*ratio));canvas.getContext('2d').drawImage(bmp,0,0,canvas.width,canvas.height);bmp.close();return canvas.toDataURL('image/webp',.82);}
$('upload').onchange=async e=>{const files=[...e.target.files];$('upload').disabled=true;let error='';for(const file of files){if(state.items.length>=12){error='The canvas holds 12 pieces. Extra images were not added.';break;}try{add(await imageData(file),file.name.replace(/\.[^.]+$/,''));}catch(e){error=e.message;}}$('upload').value='';$('upload').disabled=false;if(error)status(error);};
window.addEventListener('pagehide',persist);draw();
fetch('assets.json').then(r=>r.ok?r.json():[]).then(assets=>{if(!assets.length)return;$('starterSection').hidden=false;for(const asset of assets){const b=document.createElement('button');b.setAttribute('aria-label','Add '+asset.name);const img=document.createElement('img');img.src=asset.src;img.alt=asset.name;b.append(img);b.onclick=()=>add(asset.src,asset.name);$('starters').append(b);}}).catch(()=>{});
const context=document.modelContext;if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'get_collage',description:'Read the current collage title and editable piece positions.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:input=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected an empty object.');return {title:state.title,items:state.items.map(({src,...item})=>item)};}})).catch(()=>{});}catch{}}
