import assert from 'node:assert/strict';
import {newStory, normalizeStory, fromWeek3, moveScene} from './story.js';
const first = newStory();
first.scenes[0].title = 'Home';
first.scenes[0].items.push({id:'piece',name:'House',src:'assets/house.png',x:36,y:35,size:26,rotation:0,float:false});
first.scenes.push({...structuredClone(first.scenes[0]), id:'second',title:'Away'});
first.scenes[1].items[0].size = 10;
assert.equal(first.scenes[0].items[0].size,26);
assert.equal(moveScene(first,1,-1),0);
assert.deepEqual(first.scenes.map(s=>s.title),['Away','Home']);
assert.equal(moveScene(first,0,-1),0);
const roundTrip = normalizeStory(JSON.parse(JSON.stringify(first)));
assert.deepEqual(roundTrip.scenes.map(s=>[s.title,s.items[0].size]),[['Away',10],['Home',26]]);
const previous = {version:1,title:'Old collage',items:first.scenes[1].items};
const original = JSON.stringify(previous), migrated = fromWeek3(previous);
migrated.scenes[0].items[0].x=80;
assert.equal(JSON.stringify(previous),original);
assert.throws(()=>normalizeStory({version:2,scenes:[]}),/1–6/);
assert.throws(()=>normalizeStory({version:2,scenes:Array(7).fill(first.scenes[0])}),/1–6/);
assert.throws(()=>normalizeStory({version:2,scenes:[{items:[{src:'https://example.com/tracker.png'}]}]}),/unsupported/);
assert.throws(()=>normalizeStory({version:2,scenes:[{items:[{src:'data:image/svg+xml;base64,abc'}]}]}),/unsupported/);
console.log('PASS: scene ordering, independent copies, JSON round trip, Week 3 non-mutation, bounds and image validation. Cloud integration requires a separate live test.');
